// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceLigueHockey.Data;

namespace ServiceLigueHockey.Migrations
{
    [DbContext(typeof(ServiceLigueHockeyContext))]
    [Migration("20210319001421_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceLigueHockey.Models.EquipBd", b =>
                {
                    b.Property<int>("No_Equipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Annee_debut")
                        .HasColumnType("int");

                    b.Property<int?>("Annee_fin")
                        .HasColumnType("int");

                    b.Property<int?>("Est_Devenue_Equipe")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Equipe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ville")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("No_Equipe");

                    b.ToTable("Equipe");

                    b.HasData(
                        new
                        {
                            No_Equipe = 1,
                            Annee_debut = 1989,
                            Nom_Equipe = "Canadiensssss",
                            Ville = "Mourial"
                        },
                        new
                        {
                            No_Equipe = 2,
                            Annee_debut = 1984,
                            Nom_Equipe = "Bruns",
                            Ville = "Albany"
                        },
                        new
                        {
                            No_Equipe = 3,
                            Annee_debut = 1976,
                            Nom_Equipe = "Harfangs",
                            Ville = "Hartford"
                        },
                        new
                        {
                            No_Equipe = 4,
                            Annee_debut = 1999,
                            Nom_Equipe = "Boulettes",
                            Ville = "Victoriaville"
                        },
                        new
                        {
                            No_Equipe = 5,
                            Annee_debut = 2001,
                            Nom_Equipe = "Rocher",
                            Ville = "Percé"
                        },
                        new
                        {
                            No_Equipe = 6,
                            Annee_debut = 1986,
                            Nom_Equipe = "Pierre",
                            Ville = "Rochester"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
